language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt -r tests/requirements.txt
  - pip install robpol86-codecov

script:
  - py.test --cov-report term-missing --cov github_status tests

after_success: codecov
