language: python

python:
  - '2.7'

install: 'pip install -r requirements.txt'

before_script: 'pip install python-coveralls'

script:
  - 'py.test --cov-report term-missing --cov github_status tests'

after_success: 'coveralls -i'
